import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/styles/globals.css';
import NavigationBar from './components/navbar/NavigationBar';
import Footer from './components/footer/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'PortPai',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='absolute sticky top-0 w-full z-50'>
          <NavigationBar />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  )
}
