name: Build and deploy Node.js app to Azure Web App - portpai

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t portpai .
          docker tag portpai:latest portpai.azurecr.io/portpai:latest

      - name: Debug
        run: |
          echo "ACR_USERNAME: ${{ secrets.ACR_USERNAME }}"
          echo "ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}"
          echo "Login server: ${{ secrets.ACR_USERNAME }}"

      - name: Push Docker image to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_USERNAME }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Push Docker image
        run: docker push portpai.azurecr.io/portpai:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'portpai'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CB9DD599EBBC45B786715C520BF31E65 }}
          images: 'portpai.azurecr.io/portpai:latest'
